image: node:18

stages:
  - install
  - lint
  - test
  - start

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  allow_failure: true

test:
  stage: test
  script:
    - npm test

start:
  stage: start
  script:
    - npm start
  only:
    - master
